tests/resource/aws_cloudwatch_event_target: Use Terraform 0.11.12 and later compatible file hashing function
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSCloudWatchEventTarget_input_transformer (2.18s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.

--- FAIL: TestAccAWSCloudWatchEventTarget_input_transformer (1.81s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "input_paths" are not expected here. Did you mean to define argument "input_paths"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSCloudWatchEventTarget_input_transformer (24.60s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSCloudWatchEventTarget_input_transformer (22.38s)
```