tests/resource/aws_api_gateway_method: Use Terraform 0.11.12 and later compatible file hashing function
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAPIGatewayMethod_customauthorizer (1.85s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayMethod_customauthorizer (48.68s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayMethod_customauthorizer (35.74s)
```