resource/aws_api_gateway_authorizer: Use Terraform 0.11.12 and later compatible file hashing function in documentation and testing
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAPIGatewayAuthorizer_switchAuthType (1.83s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSAPIGatewayAuthorizer_basic (1.83s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSAPIGatewayAuthorizer_authTypeValidation (1.83s)
    testing.go:561: Step 0, expected error:

        config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.

        To match:

        authorizer_uri must be set non-empty when authorizer type is TOKEN
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayAuthorizer_cognito (21.46s)
--- PASS: TestAccAWSAPIGatewayAuthorizer_basic (40.97s)
--- PASS: TestAccAWSAPIGatewayAuthorizer_authTypeValidation (47.06s)
--- PASS: TestAccAWSAPIGatewayAuthorizer_switchAuthType (77.30s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayAuthorizer_cognito (21.97s)
--- PASS: TestAccAWSAPIGatewayAuthorizer_basic (55.51s)
--- PASS: TestAccAWSAPIGatewayAuthorizer_switchAuthType (97.25s)
--- PASS: TestAccAWSAPIGatewayAuthorizer_authTypeValidation (127.83s)
```