resource/aws_lambda_layer_version: Use Terraform 0.11.12 and later compatible file hashing function in documentation and testing
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSLambdaLayerVersion_update (1.73s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSLambdaLayerVersion_update (26.10s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSLambdaLayerVersion_update (25.75s)
```